# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

engines:
  - name: bing
    disabled: false

  - name: 360search
    engine: 360search
    shortcut: 360so
    disabled: false
  
  - name: baidu
    engine: baidu
    shortcut: baidu
    disabled: false
  
  - name: iqiyi
    engine: iqiyi
    shortcut: iq
    disabled: true

  - name: acfun
    engine: acfun
    shortcut: acf
    disabled: false

  - name: arch linux wiki
    engine: archlinux
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    distabled: false
  - name: github
    engine: github
    shortcut: gh
    disabled: false
  - name: wikipedia
    engine: wikipedia
    disabled: false
    

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "888"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json
    - csv
    - rss
ratelimit:
    enabled: true
    # 调整每秒允许的请求数
    per_second: 5  
    # 调整每分钟允许的请求数
    per_minute: 60


